### ISSUE TITLE
Is it released yet? How to download?

### ISSUE THREAD

**Issue by szfkamil** [brandonkboswell/weekly-review#1]
Ok, I am serious. It's nowhere to be found inside the Obsidian plugins; it says it's a 1.0.0 release, but I have no idea how actually to download the plugin. I exhausted the options on Git and Obsidian. I'm sorry if I'm missing something banal.

**Comment by brandonkboswell** [comment]
I've submitted it to Obsidian to make it easy to install from within Obsidian, but it's up to them when they actually accept it. Until then you can manually install it by downloading the files from https://github.com/brandonkboswell/weekly-review/releases/tag/1.0.0 and placing them in a folder in your plugins folder. To manually install a plugin: Copy over main.js, manifest.json to your vault VaultFolder/.obsidian/plugins/weekly-review/.

**Comment by szfkamil** [comment]
Thanks a lot!
