### ISSUE TITLE
Failed to load plugin on windows 10

### ISSUE THREAD

**Issue by PhoenixBodrov** [brandonkboswell/weekly-review#2]
Hi, it is amazing plugin if it would work. But i didn't get to launch it
![изображение](https://user-images.githubusercontent.com/100290554/208269472-548e30de-a2de-4d83-8d18-8ab9ffefe8ee.png)
![изображение](https://user-images.githubusercontent.com/100290554/208269477-6f747a86-bb5d-4b41-934a-bdd492b50198.png)
![изображение](https://user-images.githubusercontent.com/100290554/208269481-be6143b1-0585-429c-8ca9-ffd665920aa6.png)

Please fix that thing on windows because plug-in really cool and can save a lot of time.

**Comment by brandonkboswell** [comment]
Try copying the main.js file from the release into this folder and it should work. Let me know if that doesn't fix your problem

**Comment by matthewspear** [comment]
Plugin sounds like a great idea but I'm getting a "Failed to load plugin weekly-review" on macOS, when I try building it manually I get typescript errors!
