### ISSUE TITLE
Fork or not to fork

### ISSUE THREAD

**Issue by stanbar** [brandonkboswell/weekly-review#3]
Hi @brandonkboswell , I was looking for a plugin for doing weekly/monthly reviews and this is the closest I've found. However, my approach to doing weekly/monthly reviews is quite different. I like to do process/digest daily notes into weekly notes, then from weekly notes to monthly notes, and then from monthly notes to yearly notes. I don't want to process each individual note based on its creation date.

I would like to have two commands 1. start review and 2. mark processed.
Instead of explaining the mechanics I will illustrate you how it should work:

￼Green means the processed note,
### Start review command

![Screenshot 2023-02-14 at 14 27 57](https://user-images.githubusercontent.com/9407590/218752358-5ea1d4a0-169f-46a2-ae49-21747315325a.png)

### Mark processed command

![Screenshot 2023-02-14 at 14 28 31](https://user-images.githubusercontent.com/9407590/218752487-09373ef4-3c27-4033-90ec-7facb2c81880.png)

The processed state is stored in front matter field: processed: true/false both in daily notes, weekly notes, monthly notes and yearly notes.

Is it something you would like to see in your plugin or should I fork it to my own?

**Comment by brandonkboswell** [comment]
👋 Hey @stanbar. Your approach is still very much in the spirit of this plugin, and is very welcome here! I did the initial version based on dates only because it was the simplest solution that met my basic use case.  Let me know if you have any questions or need anything from me.
