### ISSUE TITLE
To Fork or not to Fork 2

### ISSUE THREAD

**Issue by SandmansDreams** [brandonkboswell/weekly-review#4]
Hello! I am looking for a sort of weekly, monthly, yearly recap plugin and this is the closest ive found. I am thinking something like Spotify Wrapped, including statistics like word and tag frequency, as well as a list of the notes created within the timeframe. Is that something that if I manage to make you would like to include as part of this plugin or should I make my own version? Much luck!

**Comment by brandonkboswell** [comment]
It seems like a good thematic fit to me. Bring it on.
