### ISSUE TITLE
Would be nice to be able to review updated files instead of created files

### ISSUE THREAD

**Issue by mystcreater** [brandonkboswell/weekly-review#6]
I think this plugin is absolutely genius. It helps a lot to do a rigorous review because being forced to close each tab one after another. However, in my case, I do a lot of modification and I think those files should be part of my weekly review at the same level than created file.

In any ways, this is a very nice plugin :)

**Comment by mystcreater** [comment]
Oh, I didn't noticed it was as easy as changing the ctime to mtime in the main.js file :)

**Comment by brandonkboswell** [comment]
@mystcreater This is a great idea! There is a preference page for the app, so if you want to add the preference as a PR, that would be much appreciated. I agree, that it would be useful (I would probably use that)

**Comment by brandonkboswell** [comment]
@mystcreater This is now available in v1.2.0 alongside the ability to launch your review into it's own TabGroup.
